### ISSUE TITLE
Create testgroup

### ISSUE THREAD

**Issue by amelienbawolski** [bcc-code/bcc-wp#116]
- [x] create a testgroup called: Testgroup
- [x] add these people to the testgroup:  ID 17134, ID 24688, ID 18024

**Comment by JakubC-projects** [comment]
Group uid 75bfc444-12c7-442c-92e8-52516aeb3143

**Comment by amelienbawolski** [comment]
@JakubC-projects can you add these two people to this group? 13509, 17609
