### ISSUE TITLE
Create new group with not registered employees and manager

### ISSUE THREAD

**Issue by amelienbawolski** [bcc-code/bcc-wp#128]
- [ ] create a group with all the ones from the employee and manager group and the comittee members group that haven't registered yet

**Comment by JakubC-projects** [comment]
Uid: 4a394897-7028-4d69-a5a4-22caa174fcba
Name: BCC Managers and Employees not registered to REP1223

Also for the record all groups can be viewed at https://admin.groups.bcc.no/
