### ISSUE TITLE
Kinsta Staging not responding after big load from PubSub

### ISSUE THREAD

**Issue by JakubC-projects** [bcc-code/bcc-wp#154]
Discuss how to solve this problem in the future and create follow-up.

**Comment by Bernton** [comment]
Incident happened again on 19.03 and 20.03

**Comment by Bernton** [comment]
Attempted fix in PubSub:
https://github.com/bcc-code/bcc-pubsub/pull/86

**Comment by Bernton** [comment]
Follow-up:
https://github.com/orgs/bcc-code/projects/53/views/8?sliceBy%5Bvalue%5D=Bernton&pane=issue&itemId=59133905
