### ISSUE TITLE
Widgets not working

### ISSUE THREAD

**Issue by u12206050** [bcc-code/bcc-wp#75]
Seems to be the endpoints are not executing, especially the one to get access-token.
So widgets are just blank.
![Screenshot 2023-01-16 at 17 22 09](https://user-images.githubusercontent.com/6641242/212724741-e566d3a9-7b6e-4d22-9f89-ff716db9f98f.png)
![Screenshot 2023-01-16 at 17 23 57](https://user-images.githubusercontent.com/6641242/212725077-301d7935-2415-4b24-8db9-e8a6b7faa313.png)

Have tried both with query param and path. Current theme is built on Elementor.

**Comment by rvanoord** [comment]
The /bcc-login/access-token endpoint often works after saving "permalinks" configuration in WP. Does that help?

**Comment by u12206050** [comment]
Yes have tried that. Didn't help

**Comment by u12206050** [comment]
Saw now there was an even newer version: 1.1.122 which works!
Thanks
