### ISSUE TITLE
Add option to choose avsenderorganisasjon in admin panel

### ISSUE THREAD

**Issue by amelienbawolski** [bcc-code/bcc-wp#92]
<img width="413" alt="image" src="https://github.com/bcc-code/bcc-wp/assets/107836832/5b2c3282-15ad-4f67-84df-296f0f194b04">
 
Acceptance criteria:
1. add "avsendeorganisasjon" - dropdown should inlcude either all posible organisations from members 
2. or to start with BCC-FORBUNDET, BCC NORGE, BCC EVENT,

**Comment by cs1m0n** [comment]
@amelienbawolski I'm waiting for the list.
