### ISSUE TITLE
Update name of role "Representant" to Representative

### ISSUE THREAD

**Issue by amelienbawolski** [bcc-code/bcc-wp#96]
<img width="99" alt="image" src="https://github.com/bcc-code/bcc-wp/assets/107836832/1eebf8aa-a3be-44b0-9f8b-f97caf29a746">

as shown in this picture:
![image](https://github.com/bcc-code/bcc-wp/assets/107836832/9c3b3bfd-547f-4330-9721-4843aba51e53)

**Comment by cs1m0n** [comment]
I think it's the other way around. They want the roles in Norwegian. @amelienbawolski

**Comment by amelienbawolski** [comment]
@cs1m0n ah okay but than it should be okay now?

**Comment by cs1m0n** [comment]
Yes
